include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    dead_code: warning
    unused_local_variable: warning
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - sort_child_properties_last
    - unawaited_futures
    - use_key_in_widget_constructors
